app:
  elastic_search_uri: https://elastic:PleaseChangeMe@localhost:9200
spring:
  ssl:
    bundle:
#      jks:
#        server:
#          key:
#            alias: "server"
#          keystore:
#            location: "classpath:server.p12"
#            password: "secret"
#            type: "PKCS12"
      pem:
        client:
          truststore:
            certificate: "classpath:certs/elastic-search-docker.pem"
logging.level:
  org:
    apache:
      http: TRACE